apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zxj2a4ncs-python
  janus-idp.io/tekton: zxj2a4ncs-python
  backstage.io/kubernetes-id: zxj2a4ncs-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zxj2a4ncs-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
