apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zxj2a4ncs-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zxj2a4ncs-python 
  name: zxj2a4ncs-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zxj2a4ncs-python 
